codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,files,footer"
  show_carryforward_flags: true

coverage:
  status:
    project:
      default:
        informational: true
      worker-manager:
        flags: [worker-manager]
        target: 85%
      prometheus:
        flags: [prometheus]
        target: 85%
      sizing:
        flags: [sizing]
        target: 85%
    patch:
      default:
        informational: true

flags:
  worker-manager:
    paths: [packages/worker-manager/src/]
    carryforward: true
  prometheus:
    paths: [packages/plugin-prometheus/src/]
    carryforward: true
  sizing:
    paths: [packages/plugin-container-sizing/src/]
    carryforward: true

github_checks:
  annotations: true
