injectWorkspacePackages: true
packages:
  - 'packages/**'
  - 'examples/**'
  - 'benchmarks'

catalog:
  "@types/node": "^26.2.0"
  "@vitest/coverage-v8": "^4.1.10"
  tsdown: "^0.22.14"
  typescript: "^7.0.2"
  vitest: "^4.1.10"
  vite: "^8.2.1"
